name: Build Image

on:
  pull_request:
    branches:
      - master
    paths:
      # '*' matches any character except '/'
      - 'image/*'
      - '.github/workflows/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build & Push Image
        run: |
          cd image
          IMAGE_NAME=ringcentral/vnc-chrome-mvn
          VERSION="$(awk -F '[:]'  '/FROM/ {print $2}' Dockerfile)"
          docker build --tag ${IMAGE_NAME} --file Dockerfile .
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${VERSION}"
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"

          docker push "${IMAGE_NAME}:${VERSION}"
          docker push "${IMAGE_NAME}:latest"